version: '2.0'

networks:
  diag_network:
    driver: bridge
    driver_opts:     
      com.docker.network.bridge.name: diag
    ipam:
      driver: default
      config:
        - subnet: 192.168.72.0/24
          gateway: 192.168.72.1

services:
 tshark:
  container_name: tshark  
  build: ./
  restart: always 
  entrypoint:
    - tshark
    - -t
    - u
    - -Y
    - "gsmtap and not icmp"
    #- -w
    #- /data/capture.pcap
  volumes: 
    - ./data:/data
  networks:
    diag_network:
      ipv4_address: 192.168.72.10
 scat:
  container_name: scat  
  build: ./
  links:
    - tshark
  restart: always 
  devices:
   - /dev/bus/usb/003/024
  networks:
    diag_network:
      ipv4_address: 192.168.72.20
  entrypoint:
   - python3
   - scat.py
   - -t
   - "qc"
   - -u
   - -a
   - 003:024
   - -H  
   - "192.168.72.10"
